package com.example.driveenrollappp

object SqlTable {

    const val admin = "CREATE TABLE ADMIN (ID INTEGER PRIMARY KEY AUTOINCREMENT,USER_NAME TEXT DEFAULT '',"+
            "PASSWORD TEXT DEFUALT '',MOBILE TEXT DEFUALT '')"

    const val member = "CREATE TABLE MEMBER (ID INTEGER PRIMARY KEY AUTOINCREMENT,FIRST_NAME TEXT DEFAULT '',"+
            "LAST_NAME TEXT DEFAULT '',GENDER TEXT DEFAULT '',AGE TEXT DEFAULT '',WEIGHT TEXT DEFAULT '',MOBILE TEXT DEFAULT '',"+
            "ADDRESS TEXT DEFAULT '',DATE_OF_JOINING TEXT DEFAULT '',MEMBERSHIP TEXT DEFAULT '',EXPIRE_ON TEXT DEFAULT '',"+
            "DISCOUNT TEXT DEFAULT '',TOTAL TEXT DEFAULT '',IMAGE_PATH,STATUS TEXT DEFAULT 'A')"


    const val fee = "CREATE TABLE FEE (ID INTEGER PRIMARY KEY AUTOINCREMENT,TWO_WEEK TEXT DEFAULT '',FOUR_WEEK TEXT DEFAULT '',"+
        "EIGHT_WEEK TEXT DEFAULT '',TWELVE_WEEK TEXT DEFAULT '',FOURTEEN_WEEK TEXT DEFAULT '')"

}
//IMAGE_PATH TEXT DEFAULT '',